version: "3.3"

services:
    pimoroni-christmas:
        container_name: mattgleich/pimoroni-christmas
        privileged: true
        image: "mattgleich/pimoroni-christmas"
        restart: unless-stoped